---
title: "here are some plotly plots"
output: 
  html_document:
    toc: true
    toc_float: true
---

Here's the tidyverse.
```{r, message=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Let's load the AirBnB dataset

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>  
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
         )
```

Let's make a scatterplot but interactive this time. 

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "\nRating:", rating) 
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~ label,
    type = "scatter", mode = "markers", alpha = 0.7
  )
```

Let's make a box plot

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

bar-chart
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

you can convert a ggplot object straight to an interactive graphic using ggplotly.
```{r}
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

We can recreate our boxplot in a similar way.
```{r}
box_ggplot = 
  nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```


